services:
  - type: web
    name: zealthy
    env: python
    buildCommand:
      - cd react-app && npm install && npm run build && cd ..
      - pip install -r requirements.txt
    startCommand: flask run
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
    staticPublishPath: react-app/build
